version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: omontilla
      POSTGRES_PASSWORD: Sofia28.
      POSTGRES_DB: streamdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # panel web

  api-gateway-auth:
    build:
      context: ./api-gateway-auth
    container_name: api-gateway-auth
    restart: unless-stopped
    env_file:
      - ./api-gateway-auth/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
      - ms-content

  ms-content:
    build:
      context: ./ms-content
    container_name: ms-content
    restart: unless-stopped
    env_file:
      - ./ms-content/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./shared:/tmp/videos

  ms-thumbnail-worker:
    build:
      context: ./ms-thumbnail-worker
    container_name: ms-thumbnail-worker
    restart: unless-stopped
    env_file:
      - ./ms-thumbnail-worker/.env
    depends_on:
      - rabbitmq
    volumes:
      - ./shared:/tmp/videos

volumes:
  pgdata: